development:
  adapter: postgresql
  encoding: utf8
  database: mousse_development
  username: postgres
  password: postgres
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: mousse_test
  pool: 5
  username: postgres
  password: postgres
  timeout: 5000

production:
  adapter: postgresql
  database: d2ieomvbbdbr8k
  username: byaaeghjbkyfzy
  password: JGi5HYNaWh0H9SRfxPcZWG32MO
  port: 5432
  pool: 5
  timeout: 5000
